networks:
  default:
    external:
      name: roboshop
volumes:
  mongodb: #docker volume create mongodb
  redis:
  mysql:
  rabbitmq:

version: '3.8'

services:
  web:
    build:
      context: .
    ports:
      - "80:80"

  shipping:
    image: shipping:v1
    ports:
      - "8080:8080"


  mongodb:
    image: mongodb:v1
    container_name: mongodb
    volumes:
    - source: mongodb
      target: /data/db
      type: volume
    # networks:
    # - roboshop

  catalogue:
    image: catalogue:v1
    container_name: catalogue
    # networks:
    # - roboshop
    depends_on:
    - mongodb

  web: 
    build:
    image: web:v1
    container_name: web
    ports:
    - "80:80"
    depends_on:
    - catalogue
    - cart
    - user
    - shipping
    - payment
    
  redis:
    image: redis
    container_name: redis
    volumes:
    - source: redis
      target: /data
      type: volume

  user:
    image: user:v1
    container_name: user
    depends_on:
    - redis
    - mongodb

  cart:
    image: cart:v1
    container_name: cart
    depends_on:
    - redis
    - catalogue

  