version: '3.8'

networks:
  default:
    external:
      name: roboshop

volumes:
  mongodb:
  redis:
  mysql:
  rabbitmq:

services:
  mongodb:
    build:
      context: ./mongodb
    image: mongodb:v1
    container_name: mongodb
    volumes:
      - mongodb:/data/db

  catalogue:
    build:
      context: ./catalogue
    image: catalogue:v1
    container_name: catalogue
    depends_on:
      - mongodb

  web:
    build:
      context: ./web
    image: web:v1
    container_name: web
    ports:
      - "80:80"
    depends_on:
      - catalogue
      - cart
      - user
      - shipping
      - payment

  redis:
    image: redis
    container_name: redis
    volumes:
      - redis:/data

  user:
    build:
      context: ./user
    image: user:v1
    container_name: user
    depends_on:
      - redis
      - mongodb

  cart:
    build:
      context: ./cart
    image: cart:v1
    container_name: cart
    depends_on:
      - redis
      - catalogue

  mysql:
    build:
      context: ./mysql
    image: mysql:v1
    container_name: mysql
    volumes:
      - mysql:/var/lib/mysql

  shipping:
    build:
      context: ./shipping
    image: shipping:v1
    container_name: shipping
    depends_on:
      - mysql

  rabbitmq:
    image: rabbitmq
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=roboshop
      - RABBITMQ_DEFAULT_PASS=roboshop123
    volumes:
      - rabbitmq:/var/lib/rabbitmq

  payment:
    build:
      context: ./payment
    image: payment:v1
    container_name: payment
    depends_on:
      - rabbitmq
      - user
      - cart
